### PR TITLE
Implementation of  beginning of new UI

### PR DESCRIPTION
**Pull request by NicklasHidesjo**
implemented the awesome stuff that Malva and Frida has made into the main menu UI

### CODE REVIEW

**Review by user1b2h5tfaj2 — APPROVED** [review]
Eeeemmm, sure

Best regards, The board of OmpaLompa kingdom.
<p align="left">
  

_Forever grateful, Ompalompa Erste Reich._
<br/>

**Review by malvamalmgren — APPROVED** [review]
UwU UI

**Review by malvamalmgren — APPROVED** [review]
UWU MF

**Review by Linus-Jonsson — APPROVED** [review]

**Review by malvamalmgren — APPROVED** [review]
STAHP

**Review by user1b2h5tfaj2 — APPROVED** [review]
OINK

**Review by malvamalmgren — APPROVED** [review]
I'VE HAD ENÖFF

**Comment by NicklasHidesjo** [comment]
BUGS!!!

**Pull request merged**
