### PR TITLE
New level "Ompa Lompa"

### PR DESCRIPTION
**Pull request by user1b2h5tfaj2**
## Description
The new Ompa Lompa level. This is work in progress and is not ready for a merge.

## DoD
- [x] Change traps from sprites to actual traps.
   - [x] Implement "Death plant"
   - [x] Implement "Fire trap"
   - [x] Implement "Saw blade"
      <s> Add visual path</s> //Still needs implementation
   - [x] Implement "Spinning trap"
- [x] Traps are set to right order layer.
- [x] Map objects are set to right order layer.
- [x] Colliders to level objects
- [x] Fix archway
- [x] **Test level before merge**

Best regards, The board of OmpaLompa kingdom.
<p align="left">
  

_Forever grateful, Ompalompa Erste Reich._
<br/>

### CODE REVIEW

**Review by Linus-Jonsson — DISMISSED** [review]

**Review by NicklasHidesjo — APPROVED** [review]
bugs approve

**Review by NicklasHidesjo — DISMISSED** [review]

**Review by NicklasHidesjo — APPROVED** [review]
the bugs are happy to move into 
A whole new world
A new fantastic point of view
No one to tell us, "No"
Or where to go
Or say we're only dreaming
A whole new world
A dazzling place I never knew
But when I'm way up here
It's crystal clear
That now I'm in a whole new world with you

the bugs thank you and salute you!

**Review by malvamalmgren — APPROVED** [review]
UwU

**Review by Linus-Jonsson — APPROVED** [review]
EXCITING STUFF!

**Pull request merged**
