### PR TITLE
Pause menu insert swear word here

### PR DESCRIPTION
**Pull request by user1b2h5tfaj2**
Merge now mad what de fuck

Best regards, The board of OmpaLompa kingdom.
<br/>
<p align="center">
  
</p>

_Forever grateful, Ompalompa Erste Reich._
<br/>

### CODE REVIEW

**Review by NicklasHidesjo — APPROVED** [review]

**Comment by malvamalmgren** [comment]
ლ(ಠ_ಠლ)

**Review by Linus-Jonsson — APPROVED** [review]
FUCK YEAH!!!

**Review by malvamalmgren — APPROVED** [review]
(ﾉ◕ヮ◕)ﾉ*:･ﾟ✧

**Comment by user1b2h5tfaj2** [comment]
Ding, dong, **done**!

**Pull request merged**
